"""Package cyberbullying - Outils pour le projet de détection de cyberharcèlement."""

from cyberbullying.config import (
    ANALYSIS_BY_EMBEDDING_DIR,
    ANALYSIS_DIR,
    ANALYSIS_PROJECT_DIR,
    CHECKPOINTS_DIR,
    DATA_DIR,
    DATA_PATHS,
    DATASET_FILES,
    ERROR_ANALYSIS_DIR,
    ERROR_REPORTS_DIR,
    EXPERIMENTS_DIR,
    MODELS_DIR,
    OUTPUTS_DIR,
    PRETRAINED_BERT_DIR,
    PRETRAINED_MODELS_DIR,
    PRETRAINED_ROBERTA_DIR,
    PROCESSED_DATA_DIR,
    RAW_DATA_DIR,
    REPORTS_DIR,
    ROOT_DIR,
    TRAINED_MODELS_DIR,
    WANDB_DIR,
)
from cyberbullying.embedder import (
    AggregationMethod,
    EmbeddingError,
    EmbeddingMethod,
    GlovePathRequiredError,
    MissingDependencyError,
    UnknownMethodError,
    apply_bow_embedding,
    apply_glove_embedding,
    apply_tfidf_embedding,
    apply_word2vec_embedding,
    bow_embedding,
    embed_texts,
    glove_embedding,
    load_glove_model,
    tfidf_embedding,
    train_glove_model,
    word2vec_embedding,
)
from cyberbullying.feature_engineering import (
    apply_feature_engineering,
    clean_text,
    count_capitals,
    count_characters,
    count_hashtags,
    count_mentions,
    count_urls,
    count_words,
)
from cyberbullying.loading import (
    ColumnNotFoundError,
    DatasetColumnMismatchError,
    InvalidBinaryLabelError,
    binary_load_data,
    merge_datasets,
    multiclass_load_data,
)
from cyberbullying.train import (
    get_df_split, 
    test_model, 
    train_model,
    hyperparam_search,
)

__all__ = [
    # Config
    "ROOT_DIR",
    "DATA_DIR",
    "RAW_DATA_DIR",
    "PROCESSED_DATA_DIR",
    "MODELS_DIR",
    "TRAINED_MODELS_DIR",
    "PRETRAINED_MODELS_DIR",
    "PRETRAINED_BERT_DIR",
    "PRETRAINED_ROBERTA_DIR",
    "DATASET_FILES",
    "DATA_PATHS",
    "OUTPUTS_DIR",
    "REPORTS_DIR",
    "ERROR_REPORTS_DIR",
    "ERROR_ANALYSIS_DIR",
    "ANALYSIS_DIR",
    "ANALYSIS_BY_EMBEDDING_DIR",
    "ANALYSIS_PROJECT_DIR",
    "EXPERIMENTS_DIR",
    "CHECKPOINTS_DIR",
    "WANDB_DIR",
    # Loading
    "binary_load_data",
    "multiclass_load_data",
    "merge_datasets",
    "ColumnNotFoundError",
    "InvalidBinaryLabelError",
    "DatasetColumnMismatchError",
    # Feature Engineering
    "count_words",
    "count_characters",
    "count_mentions",
    "count_hashtags",
    "count_urls",
    "count_capitals",
    "clean_text",
    "apply_feature_engineering",
    # Embeddings
    "tfidf_embedding",
    "apply_tfidf_embedding",
    "bow_embedding",
    "apply_bow_embedding",
    "word2vec_embedding",
    "apply_word2vec_embedding",
    "load_glove_model",
    "train_glove_model",
    "glove_embedding",
    "apply_glove_embedding",
    "embed_texts",
    "EmbeddingError",
    "MissingDependencyError",
    "GlovePathRequiredError",
    "UnknownMethodError",
    "AggregationMethod",
    "EmbeddingMethod",
    # Training
    "get_df_split",
    "train_model",
    "test_model",
    "hyperparam_search",
]

